name: Go

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main, actions]

jobs:
  build:
    name: Go Build (CGO)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16  # Update to the desired Go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: |
          go vet -v ./...
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload Code Coverage
        if: matrix.os == 'ubuntu-latest'  # Adjust condition based on your needs
        run: bash <(curl -s https://codecov.io/bash)
