name: lint

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E misspell -E revive
